### ISSUE TITLE
A request for code of paper "Increasing extreme fire weather occurrence in southeast Australia and related atmospheric drivers"

### ISSUE THREAD

**Issue by 1900pxl** [dougrichardson/dougrichardson#2]
Dear Ph.D. Richardson,

Thanks for reading!

I am a PhD student from Hohai University in China. My research is focused on compound drought and heatwave. I have recently read your paper "Increasing extreme fire weather occurrence in southeast Australia and related atmospheric drivers" in Weather and Climate Extremes, and was interested in the new Pettitt test method used there. I have found in my research that using Pettitt to test autocorrelated data results in an over-rejection of the null hypothesis, the approach you have used solves it well.

I am wondering if you could kindly send me the source program of the new Pettitt method and the necessary information about it. I promise they will be used only for research purposed. Specific acknowledgement will be made in future publications.

Thank you very much for your kind consideration and I am looking forward to your early reply.

Sincerely, yours

Xiaolong Pan

**Comment by dougrichardson** [comment]
Hi Xialong

Thanks for your message and apologies for the delayed response.

Unfortunately I did not make the code for that publication available. However, I have some code that performs the same test that I used in a more recent publication here: https://www.nature.com/articles/s41612-022-00248-4

The repository for that paper is here: https://github.com/dougrichardson/Richardson_compound_wildfire

The Pettitt test is on L346 of `functions.py` and is applied to the data in `3_trends_change_points.ipynb`. Please let me know if you have any questions.

**Comment by 1900pxl** [comment]
> Hi Xialong
> 
> Thanks for your message and apologies for the delayed response.
> 
> Unfortunately I did not make the code for that publication available. However, I have some code that performs the same test that I used in a more recent publication here: https://www.nature.com/articles/s41612-022-00248-4
> 
> The repository for that paper is here: https://github.com/dougrichardson/Richardson_compound_wildfire
> 
> The Pettitt test is on L346 of `functions.py` and is applied to the data in `3_trends_change_points.ipynb`. Please let me know if you have any questions.

**Comment by 1900pxl** [comment]
> Hi Xialong
> 
> Thanks for your message and apologies for the delayed response.
> 
> Unfortunately I did not make the code for that publication available. However, I have some code that performs the same test that I used in a more recent publication here: https://www.nature.com/articles/s41612-022-00248-4
> 
> The repository for that paper is here: https://github.com/dougrichardson/Richardson_compound_wildfire
> 
> The Pettitt test is on L346 of `functions.py` and is applied to the data in `3_trends_change_points.ipynb`. Please let me know if you have any questions.


Hi Dr. Richardson

Thanks for your reply, I have found the code for this method in one of your recent articles. 
This is really helpful for my research and I appreciate it. 
Wish you good luck in your work and happy life. Sincerely!
